language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
sudo: false
before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi;
install:
  - composer install
script:
  - vendor/bin/phpunit
