<?php

declare(strict_types = 1);

namespace PSX\Model\SchemaOrg;

use PSX\Schema\Attribute\Description;

#[Description('A Report generated by governmental or non-governmental organization.')]
class Report extends Article implements \JsonSerializable
{
    protected ?string $reportNumber = null;
    public function setReportNumber(?string $reportNumber) : void
    {
        $this->reportNumber = $reportNumber;
    }
    public function getReportNumber() : ?string
    {
        return $this->reportNumber;
    }
    public function jsonSerialize()
    {
        return (object) array_merge((array) parent::jsonSerialize(), array_filter(array('reportNumber' => $this->reportNumber), static function ($value) : bool {
            return $value !== null;
        }));
    }
}

